### ISSUE TITLE
stop按鈕消失

### ISSUE THREAD

**Issue by greyson89** [eternnoir/ToS_Bot#19]
S3 mycard版
常發生執行時消失,程式無後續動作,無崩潰訊息.
僅一次消失後,再次執行開啟程式顯示了pic error.
小米2s亦有類似情況,但是較少發生

另一個為按下電源按鍵鎖定手機,再開啟後start與stop按鈕也消失(有時是再開啟後約3秒後消失),這問題較常發生.

**Comment by eternnoir** [comment]
v0.2還會發生？
