### ISSUE TITLE
xperia Z 不太能正常執行

### ISSUE THREAD

**Issue by tp6vup54** [eternnoir/ToS_Bot#21]
xperia Z在執行時會發生第一次或第一二次可以正常執行，之後就卡住的情況。
推測跟螢幕截圖有關，附上螢幕截圖。

http://i.imgur.com/D3Gdwqw.jpg

另外附上debug log訊息：

https://www.dropbox.com/s/j1vwiyppr4cuy6v/xperia%20Z.txt

**Comment by eternnoir** [comment]
解釋一下為什麼會有這問題，首先log中抓不到珠況是因為用了截圖，而Sony的手機在截圖後下面會有一條怪異的黑色物體，導致判斷珠色的演算法會出錯。所以log中有take pic error。

而第一二次可以正常是因為為了加快判斷的準確性，會利用神魔的xml檔來讀珠。但這檔不是隨時更新，所以用了一組hash碼來判斷是否更新，沒更新就用截圖。比對的hash碼分別存在pascdid和nowcdid，當兩者一樣的時候就是檔案沒更新，此時會用截圖判斷
