### ISSUE TITLE
可以指定combo數

### ISSUE THREAD

**Issue by eternnoir** [eternnoir/ToS_Bot#23]
在選擇Strategy 的地方可以指定combo數

**Comment by eternnoir** [comment]
Server端修正完成，參數為combo。 0 為無限，如果找不到指定combo會以最大combo數回傳

**Comment by albert0731** [comment]
改成動態按鈕呈現
但combo數小的時候 常常出錯

**Comment by eternnoir** [comment]
已經更新Server嘗試解決此問題，如還有出現當掉的情況再重新上bug
