### ISSUE TITLE
判斷問號珠

### ISSUE THREAD

**Issue by eternnoir** [eternnoir/ToS_Bot#27]
新副本怪物技能，會產生問號珠

**Comment by tp6vup54** [comment]
演算法中本來已有個無用珠的選項
比較需要花功夫的為問號珠的顏色判斷。

**Comment by eternnoir** [comment]
修改https://github.com/eternnoir/ToS_Bot/blob/master/src/com/tos_bot/imageProcesser.java 中的 checkBallColor 函式

**Comment by taichunmin** [comment]
既然都已經有 Root 權限了，說不定可以改採查看 紀錄檔 的方式查看問號珠

**Comment by eternnoir** [comment]
這方法以前用過，使用/data/data/com.madhead.tos.zh/shared_prefs/com.madhead.tos.zh.xml 這個檔。之前最大瓶頸在這個檔不是珠面狀況有變動就更新，他會在換關卡、怪物死亡、施放技能這幾種狀況下才更新。不過因為問號珠開放後我就去當兵了，還沒測試問號珠的情形

**Comment by eternnoir** [comment]
或許 #39 可以一併解決
