### ISSUE TITLE
COMBO數圖片

### ISSUE THREAD

**Issue by albert0731** [eternnoir/ToS_Bot#30]
目前動態切換COMBO的圖片我隨手用小畫家畫的
跟原始風格完全不搭
等大大改一下 並希望能跟策略選擇都弄成圓角方形排一起

**Comment by eternnoir** [comment]
@tp6vup54  只好交給你了XDD

**Comment by tp6vup54** [comment]
只要有空我就做，但是可惡的ypc不讓我閒..

**Comment by eternnoir** [comment]
聽說DIVA Team瘋狂被轟炸？XDD

**Comment by eternnoir** [comment]
#35
