### ISSUE TITLE
設定頁面

### ISSUE THREAD

**Issue by eternnoir** [eternnoir/ToS_Bot#36]
讓主頁只留下一個開始的icon，所有設定轉移到另外一頁專門的設定頁面去修改

**Comment by albert0731** [comment]
我當時故意把我的版本改成 策略根combo按鈕持續顯示
不用停止戰鬥就能快速更改的說XDDD

**Comment by eternnoir** [comment]
暫定進入設定頁後有三個子分頁
Solver
--Server Site
--maxMove
--maxCombo(估計會被換去浮動視窗)
Image
--珠面最左上角的座標
--珠面寬
touchEvent
--所有移動需要的event

**Comment by eternnoir** [comment]
使用http://developer.android.com/reference/android/content/SharedPreferences.html

**Comment by eternnoir** [comment]
進度50%，完成touchEvent的設定頁面

**Comment by eternnoir** [comment]
@nell83917 那是原始碼的壓縮檔，解壓縮後自行compile成apk安裝進手機

**Comment by eternnoir** [comment]
請問是哪裡出現xx呢？如果跟ATEC有關的話記得把專案裡的submodule加到eclipse java的lib中
