### ISSUE TITLE
當使用者按住螢幕後需要暫時停止程式運行

### ISSUE THREAD

**Issue by tp6vup54** [eternnoir/ToS_Bot#6]
需求分兩部份：
1. 需要給使用者使用技能或思考是否要使用技能，或鎖定敵人等戰術考量的時間。
2. 3.0版後新增需要固定combo才能攻擊的敵人，目前的演算法無法達到這一點，為此製作special case成本報酬不成正比，遇到此類敵人還是需要使用者自行轉珠。

實做上建議當使用者按住螢幕後暫停程式(sleep or something)，手指移開螢幕後5秒開始運作。

**Comment by eternnoir** [comment]
http://www.kpbird.com/2013/03/android-detect-global-touch-event.html

**Comment by eternnoir** [comment]
很難在Service中Listen Global event
