### ISSUE TITLE
可以開始轉珠與否的狀態確認

### ISSUE THREAD

**Issue by tp6vup54** [eternnoir/ToS_Bot#9]
目前的方法是轉珠完後等待12秒再次擷取畫面。

此方法可以應付大部分的狀態，但是遇到天降神珠(16 combo up)加上boss動畫過長時，12秒會有不夠的情況。

單純將時間加長會拖延到一般戰鬥，並非治本的方法，因此建議的方法為：
每3秒或3秒以下擷一張圖確認是否進入戰鬥，一旦進入後再等待3秒給使用者思考戰術緩衝等，再開始正常運作。

難點可能在如何從圖片上確認是否進入戰鬥。

**Comment by eternnoir** [comment]
目前的Code是確定轉珠等12秒，如果畫面擷取有誤3秒後會重新擷取。基本上沒進入戰鬥在從圖片轉成珠的陣列時就會出錯，等三秒重試
